#! /usr/bin/env ruby
# encoding: utf-8

module Enumerable
  def ordenar_frecuencias
      histo = inject(Hash.new(0)) {|hash, x| hash[x]+=1; hash}
      sort_by { |x| [histo[x], x] }
  end
end

x = [1, 1, 1, 4, 5, 4, 1, 3, 3, 7, 8].ordenar_frecuencias

p x
