#! /usr/bin/env ruby
#  coding: utf-8

module Enumerable

  def cartesiano(beta)

    res = [ ]

    each {|x| beta.each {|y| res << [ x, y] }}

    return res
  end
end

alfa = [ 'a', 'b', 'c', 'd', 'e']

beta = (0..9).to_a

prodcarter = alfa.cartesiano(beta)

p prodcarter

print 'El número de elementos del este producto cartesiano'
print "\n"
print 'es igual a '
print prodcarter.length
print "\n"
print "El número de elementos de alfa es "
print alfa.length
print "\n"
print "El número de elementos de beta es "
print beta.length
print "\n"



